sudo: required

services:
  - docker

language: java

jdk:
  - openjdk8
  - openjdk11

before_install:
  - docker --version
  - docker pull ghusta/postgres-world-db:2.3
  - docker run -d --name world-db -e POSTGRES_USER="world" -e POSTGRES_PASSWORD="world123" -p 5510:5432 ghusta/postgres-world-db:2.3
  - docker ps

install:
  - mvn --batch-mode --show-version dependency:go-offline

script:
  - mvn --batch-mode --show-version -Pgen-hibernate-tools test

after_success:
  - echo "Sources générées par Hibernate Tools "
  - ls -lhR target/generated-sources/hibernate/
