sudo: required

services:
  - docker

language: java

jdk:
  - openjdk8
  - openjdk11

before_install:
  - docker --version
  - docker pull ghusta/postgres-world-db:2.2
  - docker run -d --name world-db -e POSTGRES_USER="world" -e POSTGRES_PASSWORD="world123" -p 5510:5432 ghusta/postgres-world-db:2.2
  - docker ps

install:
  - mvn dependency:go-offline -B -V

script:
  - mvn test -Pgen-hibernate-tools
